VERSION=1.1.1.3
PACKAGE=zcs-lib-redstone-xmlrpc
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=free/zcs-libs
ARCHITECTURE=All
PRIORITY=optional
DEPENDS=
DESCRIPTION=Redstone XML-RPC library
REDMINE_UPLOAD_PROJECT=zcs-lib-redstone-xmlrpc
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
